<a href="https://colab.research.google.com/github/coltongerth/degradation/blob/main/degradation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%capture
# !pip install fiona
# !pip install shapely
!pip install dask
!pip install jupyter-server-proxy
!pip install affine==2.3.1
!pip install attrs==22.2.0
!pip install bounded-pool-executor==0.0.3
!pip install certifi==2022.12.7
!pip install click==8.1.3
!pip install click-plugins==1.1.1
!pip install cligj==0.7.2
!pip install numpy==1.24.1
!pip install python-dateutil==2.8.2
!pip install pytz==2022.7
!pip install rasterio==1.3.4
!pip install scipy==1.10.0
!pip install six==1.16.0
!pip install snuggs==1.4.7
!pip install statsmodels==0.13.5
!pip install git+https://github.com/lankston-consulting/lcutils

Zonal Statistics and Degradation class instantiation.

In [1]:
# import fiona
# import cupy as cp
# import pickle
import os
import rasterio
import asyncio
import warnings
import gc
import mmap
import dask
# import geopandas as gpd
import numpy as np
import dask.array as da
import dask.dataframe as dd
# from shapely.geometry import shape
from dask.delayed import delayed
from dask.distributed import Client, LocalCluster
from rasterio.windows import Window
from rasterio.profiles import DefaultGTiffProfile
from rasterio.mask import mask
from statsmodels.regression.linear_model import OLS, GLSAR
from scipy import stats as st
from datetime import datetime
from bounded_pool_executor import BoundedProcessPoolExecutor
from concurrent.futures import ProcessPoolExecutor, wait, FIRST_COMPLETED, ALL_COMPLETED
from dotenv import load_dotenv
from lcutils import gcs, eet
from google.colab import drive




drive.mount('/content/gdrive')
path_to_credentials = "gdrive/MyDrive/fuelcast-storage-credentials.json"
gch = gcs.GcsTools(use_service_account={"keyfile": path_to_credentials})
warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=UserWarning)

nodata = -32,768


class Stat(object):
    def __init__(self, zone):
        self.zone = zone
        self.mean = 0
        self.std = 0
        self.n = 0
        self.data = list()

    def add_data(self, data):
        self.data.append(data)

    def calc_stats(self):
        if self.data:
            self.data = np.array(self.data)
            self.data = np.ma.masked_where(self.data < 0, self.data)
            self.mean = np.ma.mean(self.data, axis=0)
            self.std = np.ma.std(self.data, axis=0)
            self.n = np.ma.count(self.data, axis=0)
            self.n = np.ma.masked_where(
                self.n <= 0, self.n
            )

            # Clean up the object to reduce memory footprint
            del self.data


class StatAccumulator(object):
    def __init__(self, update_size=500):
        self.statistics = dict()
        self._update_size = update_size
        self.merged_stats = dict()

    def update(self, zone, new_stats, force=False):
        if zone not in self.statistics:
            self.statistics[zone] = [new_stats]
        else:
            stats_col = self.statistics[zone]
            old_stats = stats_col[-1]

            if len(old_stats.data) > self._update_size or force:
                old_stats.calc_stats()
                self.statistics[zone].append(new_stats)
            else:
                old_stats.data.extend(new_stats.data)
        return

    def update_cochrane(self, zone, new_stats):
        if zone not in self.statistics:
            self.statistics[zone] = new_stats
        else:
            old_stats = self.statistics[zone]

            tn = old_stats.n + new_stats.n
            tmean = (old_stats.n * old_stats.mean + new_stats.n * new_stats.mean) / tn

            t1 = np.ma.add(old_stats.n - 1, np.power(old_stats.std, 2))
            t2 = np.ma.add(new_stats.n - 1, np.power(new_stats.std, 2))
            tr = np.ma.multiply(t1, t2)

            t1 = np.ma.multiply(old_stats.n, new_stats.n)
            t2 = np.ma.add(old_stats.n, new_stats.n)
            tt = np.ma.divide(t1, t2)

            t1 = np.ma.power(old_stats.mean, 2)
            t2 = np.ma.power(new_stats.mean, 2)
            tu = np.ma.add(t1, t2)

            tv = np.ma.multiply(np.ma.multiply(old_stats.mean, new_stats.mean), 2)

            tx = np.ma.add(old_stats.n + new_stats.n - 1, tr)
            xs = np.ma.subtract(tu, tv)
            xt = np.ma.multiply(tt, xs)
            xu = np.ma.add(tx, xt)

            z = np.ma.divide(xu, tx)

            tsd = np.ma.sqrt(z)

            new_stats.n = tn
            new_stats.mean = tmean
            new_stats.std = tsd
            self.statistics[zone] = new_stats

    def update_multiple(self, zone):
        self.statistics[zone][-1].calc_stats()

        def collect(data, tn, tx, txx):
            n = data.n
            mean = data.mean
            sd = data.std
            x = n * mean
            xx = sd**2 * (n - 1) + x**2 / n
            tn = tn + n
            tx = tx + x
            txx = txx + xx

            return tn, tx, txx

        tn, tx, txx = 0, 0, 0
        for data in self.statistics[zone]:
            tn, tx, txx = collect(data, tn, tx, txx)

        tmean = tx / tn
        tsd = np.ma.sqrt(
            np.ma.divide(
                np.ma.subtract(txx, np.ma.divide(np.ma.power(tx, 2), tn)),
                np.ma.add(tn - 1),
            )
        )

        old_stats = self.statistics[zone][0]
        old_stats.mean = tmean
        old_stats.std = tsd
        old_stats.n = tn

        self.merged_stats[zone] = old_stats

        return

    def merge(self):
        self.merged_stats = dict()

        def chunk_gen(lst, n):
            for i in range(0, len(lst), n):
                yield lst[i : i + n]

        def merge_chunk(indexes):
            key_list = list(self.statistics.keys())
            for i in indexes:
                zone = key_list[i]
                self.update_multiple(zone)

        [self.update_multiple(z) for z in self.statistics]
        self.statistics = self.merged_stats
        del self.merged_stats
        gc.collect()  # Explicitly call garbage collection
        return

    def write(self, path="./output/zone_stats.csv"):
        with open(path, "w") as f:
            header = "zone, year, mean, std, n\n"
            f.write(header)

            for z in self.statistics:
                data = self.statistics[z]
                print("stats data:",data)
                for i in range(len(data.mean)):
                    line = "{0}, {1}, {2}, {3}, {4}\n".format(
                        z, i, data.mean[i], data.std[i], data.n[i]
                    )
                    f.write(line)


class ZonalStatistics(object):
    def __init__(self):
        pass

    def data_collector(self, *args, **kwargs):
        print("data collector val data:", args[0]["val_data"].shape)
        print("data collector zone data:", args[0]["zone_data"].shape)

        stats = dict()

        I = args[0]["val_data"].shape[0]
        J = args[0]["val_data"].shape[1]
        K = args[0]["val_data"].shape[2]

        for i in range(I):
            for j in range(J):
                for k in range(K):
                    zone = args[0]["zone_data"][i, j, k]
                    data = args[0]["val_data"][:, j, k]

                    if zone > 0:
                        if zone not in stats:
                            stats[zone] = Stat(zone)
                        stats[zone].add_data(data)

        return stats

    def t_test(self, *args, **kwargs):
        print("t_test val data:", args[0]["val_data"].shape)
        print("t_test zone data:", args[0]["zone_data"].shape)
        I = args[0]["zone_data"].shape[0]
        J = args[0]["zone_data"].shape[1]
        K = args[0]["zone_data"].shape[2]
        print("I:",I)
        print("J:",J)
        print("K:",K)

        output = np.empty((4, J, K), dtype="int16")
        output.fill(nodata)

        for i in range(I):
            for j in range(J):
                for k in range(K):
                    zone = args[0]["zone_data"][i, j, k]
                    data = args[0]["val_data"][:, j, k]

                    if zone > 0:
                        stat = args[0]["statistics"].statistics[zone]
                        try:
                            vals = self._t_test_strict_r_logic(stat, data)
                            if vals is not None:
                                output[:, j, k] = vals
                        except Exception as ex:
                            pass

        return output

    def _t_test_strict_r_logic(self, stat, data):
        data = np.ma.masked_where(data < 0, data)
        i_mean = np.ma.mean(data)

        if np.ma.is_masked(i_mean):
            return None

        nan_data = data.astype(float).filled(np.nan)

        p_n_adj = stat.n - 1
        p_mean_list = ((stat.mean * p_n_adj) - data) / p_n_adj
        p_mean_list = np.ma.masked_where(p_mean_list < 0, p_mean_list)

        t, p = st.ttest_rel(nan_data, p_mean_list, nan_policy="omit")

        if np.ma.is_masked(t):
            return None

        years = np.array(list(range(len(p_mean_list))))

        mask_years = np.ma.array(years.astype(float), mask=p_mean_list.mask)
        nan_years = mask_years.filled(np.nan)
        pop_trend_model = GLSAR(p_mean_list, nan_years, missing="drop")
        pop_trend_result = pop_trend_model.fit()

        mask_years = np.ma.array(years.astype(float), mask=data.mask)
        nan_years = mask_years.filled(np.nan)
        ind_trend_model = GLSAR(data, nan_years, missing="drop")
        ind_trend_result = ind_trend_model.fit()

        pop_slope = pop_trend_result.params[0]
        ind_slope = ind_trend_result.params[0]

        slope_diff = ind_slope - pop_slope
        slope_se = ind_trend_result.bse
        slope_t = slope_diff / slope_se

        df = ind_trend_result.nobs - len(ind_trend_result.params)

        slope_p = st.t.sf(np.abs(slope_t), df=df) * 2

        vals = np.array([t, p, slope_t[0], slope_p[0]])

        return vals


class Degradation(object):
    def __init__(self, *args, **kwargs):
        return

    def degradation(self, data):

        I = data.shape[0]
        J = data.shape[1]
        K = data.shape[2]
        output = np.empty((I, J, K))

        for i in range(I):
            for j in range(J):
                for k in range(K):
                    val = data[i, j, k]
                    output[i, j, k] = val
        return output


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Inputs

In [2]:
zone_name = "BpsZonRobGb_wgs84_nc"
# zone_name = "RMUDissolve_2_GCS"
gcs_degradation_path = "gs://fuelcast-data/degradation/"
gcs_rpms_path = "gs://fuelcast-data/rpms/"

zone_raster_path = f"{gcs_degradation_path}{zone_name}/{zone_name}.tif"
# zone_raster_path = f"gdrive/MyDrive/{zone_name}/{zone_name}.shp"
data_raster_path = f"./data/{zone_name}/rpms_stack.tif"
dummy_path = "./test.tif"

In [3]:
from IPython.display import display
from dask.distributed import Client, LocalCluster


# Display the Dask dashboard link


out_path = [
    f"./output/{zone_name}_mean_t.tif",
    f"./output/{zone_name}_mean_p_adj.tif",
    f"./output/{zone_name}_slope_t.tif",
    f"./output/{zone_name}_slope_p_adj.tif",
]

if not os.path.exists("./output/"):
    os.makedirs("./output/")

BLOCKSIZE = 1024
nodata = -32768


def read_window(zone_file, data_file, z_window):
    with rasterio.Env(GOOGLE_APPLICATION_CREDENTIALS=os.getenv("GOOGLE_APPLICATION_CREDENTIALS", path_to_credentials)):
        with rasterio.open(zone_file) as zone_src:
            zone = zone_src.read(window=z_window)
            bounds = zone_src.window_bounds(z_window)

        with rasterio.open(data_file) as data_src:
            d_window = data_src.window(*bounds)
            d_window = d_window.intersection(Window(0, 0, data_src.width, data_src.height))
            out_shape = (data_src.count, round(d_window.height), round(d_window.width))
            data = data_src.read(window=d_window, out_shape=out_shape)
            if data.shape[2] < z_window.width:
                data = data[:, :, :z_window.width]
            if data.shape[1] < z_window.height:
                data = data[:, :z_window.height, :]
        # print(f"window zone: {zone} window data: {data} window d_window: {d_window}")
    return zone, data, d_window

def process_window(task, func, accumulator, zone, data, window, out_rasters=None, **kwargs):
    if task == "collect":
        # print(zone)
        # print(zone.shape)
        # print(data)
        mask = (data != nodata)  # Create a mask for valid data
        valid_data = data[mask]  # Use the mask to get valid data
        if valid_data.size > 0:  # Check if there is any valid data
            accumulator.update(data[mask], valid_data)
        mask = (zone != nodata)  # Create a mask for valid data
        valid_data = zone[mask]  # Use the mask to get valid data
        if valid_data.size > 0:  # Check if there is any valid data
            accumulator.update(zone[mask], valid_data)

    else:
        # print(f"Original data shape: {data.shape}")
        # print(f"Window dimensions: height={window.height}, width={window.width}")
        func_args = {"zone_data": zone, "val_data": data, "statistics": accumulator}
        result = func(func_args)

        # # Ensure result shape matches the window shape
        result = [
                  result[i, :, :].reshape(
                      1, result.shape[1], result.shape[2]
                  )
                  for i in range(4)
                  ]

        # Write the result to the respective raster output files
        print("result 0:",result[0])
        print("result 1:",result[1])
        print("result 2:",result[2])
        print("result 3:",result[3])
        if out_rasters:
            mean_t_raster, mean_p_raster, slope_t_raster, slope_p_raster = out_rasters
            mean_t_raster.write(result[0], window=window)
            mean_p_raster.write(result[1], window=window)
            slope_t_raster.write(result[2], window=window)
            slope_p_raster.write(result[3], window=window)

        return result

def main_statistics(task, zone_file, data_file, out_files, queue_size=2, batch_size=3, *args, **kwargs):
    zs = ZonalStatistics()

    if task == "collect":
        accumulator = StatAccumulator()
        func = zs.data_collector
    elif task == "degradation":
        if "acc" in kwargs:
            accumulator = kwargs["acc"]
        else:
            raise ValueError()
        func = zs.t_test

    with rasterio.Env(GOOGLE_APPLICATION_CREDENTIALS=os.getenv("GOOGLE_APPLICATION_CREDENTIALS", path_to_credentials)):
        with rasterio.open(zone_file) as zone_src:
            profile = zone_src.profile
            profile.update(blockxsize=BLOCKSIZE, blockysize=BLOCKSIZE, tiled=True, dtype="int16", compress="DEFLATE", nodata=nodata)
             # Adjust the cluster configuration for better performance
            cluster = LocalCluster(n_workers=queue_size, threads_per_worker=3, memory_limit='2GB')
            client = Client(cluster, timeout="120s")
            display(client)


            if task == "degradation":
                mean_t_raster = rasterio.open(out_files[0], "w", **profile)
                mean_p_raster = rasterio.open(out_files[1], "w", **profile)
                slope_t_raster = rasterio.open(out_files[2], "w", **profile)
                slope_p_raster = rasterio.open(out_files[3], "w", **profile)
                out_rasters = (mean_t_raster, mean_p_raster, slope_t_raster, slope_p_raster)
            else:
                out_rasters = None

            zone_windows = [window for ij, window in zone_src.block_windows()]


            # Use only a small subset of zone_windows for testing
            subset_zone_windows = zone_windows[:100]

            delayed_tasks = []
            for z_window in subset_zone_windows:
                delayed_task = delayed(read_window)(zone_file, data_file, z_window)
                delayed_tasks.append(delayed_task)

            results = dask.compute(*delayed_tasks)

            for result in results:
                zone, data, d_window = result
                process_window(task, func, accumulator, zone, data, d_window, out_rasters=out_rasters, **kwargs)

            if task == "collect":
                accumulator.merge()
                accumulator.write()
            else:
                # Close the raster files
                mean_t_raster.close()
                mean_p_raster.close()
                slope_t_raster.close()
                slope_p_raster.close()

            client.close()
    return accumulator

def raster_stacker(id, in_ds, out_ds, bounds, chunk_size=1024):
    with rasterio.open(in_ds) as src_ds:
        # Calculate the window for the given bounds
        # [-109.061279,36.976227,-102.052002,40.988192]
        win = src_ds.window(
            left=bounds[0],
            bottom=bounds[1],
            right=bounds[2],
            top=bounds[3],

        )

        # win = src_ds.window(
        #     bottom=bounds.bottom,
        #     right=bounds.right,
        #     top=bounds.top,
        #     left=bounds.left,
        # )

        # Convert window dimensions to integers
        win_width = int(win.width)
        win_height = int(win.height)

        # Calculate the number of chunks needed for the window
        num_chunks_x = (win_width + chunk_size - 1) // chunk_size
        num_chunks_y = (win_height + chunk_size - 1) // chunk_size

        for i in range(num_chunks_x):
            for j in range(num_chunks_y):
                col_off = int(win.col_off) + i * chunk_size
                row_off = int(win.row_off) + j * chunk_size
                width = min(chunk_size, win_width - i * chunk_size)
                height = min(chunk_size, win_height - j * chunk_size)

                # Ensure the chunk window is within the raster bounds
                if col_off < 0 or col_off >= src_ds.width:
                    # print(f"Skipping chunk ({i}, {j}): col_off out of range col_off={col_off}")
                    continue
                if row_off < 0 or row_off >= src_ds.height:
                    # print(f"Skipping chunk ({i}, {j}): row_off out of range row_off={row_off}")
                    continue
                if col_off + width > src_ds.width:
                    width = src_ds.width - col_off
                if row_off + height > src_ds.height:
                    height = src_ds.height - row_off

                if width <= 0 or height <= 0:
                    # print(f"Skipping chunk ({i}, {j}): Invalid dimensions col_off={col_off}, row_off={row_off}, width={width}, height={height}")
                    continue

                chunk_win = Window(
                    col_off=col_off,
                    row_off=row_off,
                    width=width,
                    height=height,
                )

                # Log the details of the chunk being processed
                # print(f"Processing chunk ({i}, {j}): col_off={col_off}, row_off={row_off}, width={width}, height={height}")

                data = src_ds.read(1,window=chunk_win)

                # Adjust the chunk window to fit within the output dataset dimensions
                out_col_off = col_off
                out_row_off = row_off
                out_width = min(data.shape[1], out_ds.width - out_col_off)
                out_height = min(data.shape[0], out_ds.height - out_row_off)

                if out_col_off + out_width > out_ds.width or out_row_off + out_height > out_ds.height:
                    # print(f"Skipping chunk ({i}, {j}): Output window out of range out_col_off={out_col_off}, out_row_off={out_row_off}, width={out_width}, height={out_height}")
                    continue

                out_win = Window(
                    col_off=out_col_off,
                    row_off=out_row_off,
                    width=out_width,
                    height=out_height
                )

                out_ds.write_band(id, data, window=out_win)
                # print(f"Processed chunk ({i}, {j})")

async def main_run():
    with rasterio.Env(GDAL_NUM_THREADS="ALL_CPUS", verbose=2, GOOGLE_APPLICATION_CREDENTIALS=os.getenv("GOOGLE_APPLICATION_CREDENTIALS", path_to_credentials)):
        zone_ds = rasterio.open(zone_raster_path, chunks=(BLOCKSIZE, BLOCKSIZE))
        bounds = zone_ds.bounds
        bounds = [-114.174042,42.633959,-112.858429,43.608239]
        profile = zone_ds.profile
        profile.update(
            blockxsize=BLOCKSIZE,
            blockysize=BLOCKSIZE,
            tiled=True,
            compress="DEFLATE",
            predictor=2,
            BIGTIFF="Yes",
            dtype="int16"
        )

        od = f"./data/{zone_name}"
        if not os.path.exists(od):
            os.makedirs(od)

        files = [f"gs://fuelcast-data/rpms/{y}/rpms_{y}.tif" for y in range(1985, 2023) if y != 2012]

        profile.update(count=len(files))

        print("Stacking raster")

        stack_path = f"./data/{zone_name}/rpms_stack.tif"

        if os.path.exists(stack_path):
            print(f"Stacked raster {stack_path} already exists.")
        else:
            with rasterio.open(stack_path, "w", **profile) as dst:
                print(f"out: {dst} || {dst.bounds}")

                for id, layer in enumerate(files, start=1):
                    print(f"in: {layer}")
                    raster_stacker(id, layer, dst, bounds)

        print("Calculating zonal statistics")

        acc = main_statistics(
            "collect", zone_raster_path, data_raster_path, out_path, 6
        )

        print("Running degradation")
        start = datetime.now()
        main_statistics(
            "degradation", zone_raster_path, data_raster_path, out_path, 6, acc=acc
        )
        stop = datetime.now()
        print("Total runtime:", (stop - start).seconds / 60, "minutes")

        print("Finished")

await main_run()

Stacking raster
Stacked raster ./data/BpsZonRobGb_wgs84_nc/rpms_stack.tif already exists.
Calculating zonal statistics


INFO:distributed.scheduler:State start
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-adup9dnn', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-07gu78gp', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-w68yqdcf', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-4ba9m6fe', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-trjvnes2', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-_dkj_kqp', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-h_ycijir', purging
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/worker-m601jlfj', purging
INFO:distributed.diskutils:Found stale lock fi

<Client: 'tcp://127.0.0.1:40235' processes=6 threads=18, memory=11.18 GiB>

INFO:distributed.scheduler:Remove client Client-243eddae-31a0-11ef-ac1f-0242ac1c000c
INFO:distributed.core:Received 'close-stream' from tcp://127.0.0.1:37384; closing.
INFO:distributed.scheduler:Remove client Client-243eddae-31a0-11ef-ac1f-0242ac1c000c
INFO:distributed.scheduler:Close client connection: Client-243eddae-31a0-11ef-ac1f-0242ac1c000c
INFO:distributed.scheduler:State start
INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:41101
INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:33071/status
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:42329'


Running degradation


INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:44181'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:40687'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:45405'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:35643'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:36737'
INFO:distributed.scheduler:Register worker <WorkerState 'tcp://127.0.0.1:34185', name: 1, status: init, memory: 0, processing: 0>
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:34185
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:60858
INFO:distributed.scheduler:Register worker <WorkerState 'tcp://127.0.0.1:46605', name: 4, status: init, memory: 0, processing: 0>
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:46605
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:60862
INFO:distributed.scheduler:Register worker <WorkerState 'tcp://12

<Client: 'tcp://127.0.0.1:41101' processes=6 threads=18, memory=11.18 GiB>

Original data shape: (37, 128, 128)
Window dimensions: height=128.0, width=128.0
t_test val data: (37, 128, 128)
t_test zone data: (1, 128, 128)
I: 1
J: 128
K: 128
result 0: [[[-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  ...
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]]]
result 1: [[[-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  ...
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]]]
result 2: [[[-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  [-32768 -32768 -32768 ... -32768 -32768 -32768]
  ...
  [-32768 -32768 -32768 ... -32768

INFO:distributed.scheduler:Remove client Client-415e0b13-31a0-11ef-ac1f-0242ac1c000c
INFO:distributed.core:Received 'close-stream' from tcp://127.0.0.1:60920; closing.
INFO:distributed.scheduler:Remove client Client-415e0b13-31a0-11ef-ac1f-0242ac1c000c
INFO:distributed.scheduler:Close client connection: Client-415e0b13-31a0-11ef-ac1f-0242ac1c000c


Total runtime: 1.3166666666666667 minutes
Finished
